const x = "declarado fuera de la funci贸n";

function ejemploFuncion() {
    const x = "declarado dentro de la funci贸n";
    console.log("Dentro de la funci贸n");
    console.log(x);
}

console.log(x);

ejemploFuncion();

console.log("Fuera de la funci贸n");
console.log(x);

function f() {
    try {
        console.log(0);
        throw 'falso';
    } catch (e) {
        console.log(1);
        return true;
    } finally {
        console.log(3);
        return false;
    }
}

console.log(f());
